"""Feature engineering for the Market Research Data Layer (Phase 3).

Reads `processed/bars_joined/binance/<SYMBOL>/<TF>.parquet` plus the
raw daily OI metrics parquets for crowding columns, and emits
`processed/features/binance/<SYMBOL>/<TF>.parquet`.

Anti-lookahead policy: every feature for bar `i` is a function of
closed bar `i` and bars `< i`. No future bars are referenced. Pandas
`.rolling`, `.ewm`, `.shift(positive)`, and `.pct_change` with
non-negative offsets are the only time-series ops used.

Definitions and window parameters live in
`data_layer/config/features.yaml`. Feature catalog (human-readable)
is regenerated by `data_layer/scripts/refresh_summaries.py`.
"""
from __future__ import annotations

import datetime as dt
import glob
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa

from data_layer.ingest.common import write_parquet_atomic

# bars per day per timeframe
BARS_PER_DAY = {"5m": 288, "1h": 24}
BARS_PER_HOUR = {"5m": 12, "1h": 1}
TF_MIN = {"5m": 5, "1h": 60}
FUNDING_INTERVAL_MIN = 480  # 8h default for Binance perp


@dataclass(frozen=True)
class FeatureSpec:
    name: str
    description: str
    inputs: tuple[str, ...]
    window: str  # e.g. "1 bar", "24 bars", "30 days"


FEATURE_SPECS: tuple[FeatureSpec, ...] = (
    FeatureSpec("ret_1", "close pct change over 1 bar", ("close",), "1 bar"),
    FeatureSpec("ret_3", "close pct change over 3 bars", ("close",), "3 bars"),
    FeatureSpec("ret_12", "close pct change over 12 bars", ("close",), "12 bars"),
    FeatureSpec("ret_72", "close pct change over 72 bars", ("close",), "72 bars"),
    FeatureSpec("vol_close_to_close_24", "rolling std of ret_1 over 24 bars",
                ("ret_1",), "24 bars"),
    FeatureSpec("atr_14", "Wilder average true range over 14 bars",
                ("high", "low", "close"), "14 bars"),
    FeatureSpec("range_pct", "(high-low)/close on the current closed bar",
                ("high", "low", "close"), "1 bar"),
    FeatureSpec("ema_fast_minus_slow_pct",
                "(EMA(close,fast)-EMA(close,slow))/close, fast=12 slow=48",
                ("close",), "fast=12 slow=48 bars"),
    FeatureSpec("slope_ret_24", "OLS slope of log(close) over last 24 bars",
                ("close",), "24 bars"),
    FeatureSpec("vol_zscore_24",
                "z-score of ret_1 vs rolling 24-bar mean+std",
                ("ret_1",), "24 bars"),
    FeatureSpec("taker_imbalance",
                "(2*taker_buy_base - volume_base)/volume_base on closed bar",
                ("taker_buy_base", "volume_base"), "1 bar"),
    FeatureSpec("taker_quote_zscore_24",
                "z-score of taker_buy_quote vs rolling 24-bar mean+std",
                ("taker_buy_quote",), "24 bars"),
    FeatureSpec("funding_rate_zscore_30d",
                "z-score of funding_rate over rolling 30-day window; "
                "null until min_periods=7d met",
                ("funding_rate_ffill",), "30 days"),
    FeatureSpec("basis_bp",
                "(mark-index)/index*1e4; insufficient_data in Phase 2/3 "
                "(no mark/index series ingested yet)",
                ("mark", "index"), "1 bar"),
    FeatureSpec("oi_pct_change_1h", "OI pct change over 1 hour",
                ("oi_base",), "1 hour"),
    FeatureSpec("oi_pct_change_24h", "OI pct change over 24 hours",
                ("oi_base",), "24 hours"),
    FeatureSpec("oi_zscore_30d",
                "z-score of OI over rolling 30-day window; "
                "null until min_periods=7d met",
                ("oi_base",), "30 days"),
    FeatureSpec("pre_funding_30m",
                "1 if 0 < minutes_to_next_settle <= 30 else 0",
                ("funding_minutes_to_next",), "1 bar"),
    FeatureSpec("post_funding_30m",
                "1 if 0 <= minutes_since_last_settle <= 30 else 0",
                ("funding_minutes_to_next",), "1 bar"),
    FeatureSpec("funding_settle_bar",
                "1 if abs(minutes_to_next_settle) <= tf_min/2 else 0",
                ("funding_minutes_to_next",), "1 bar"),
    FeatureSpec("long_short_account_ratio",
                "joined from raw daily metrics (asof, 60min TTL)",
                ("oi_metrics",), "5 min source"),
    FeatureSpec("top_trader_position_ratio",
                "joined from raw daily metrics (asof, 60min TTL)",
                ("oi_metrics",), "5 min source"),
    FeatureSpec("taker_long_short_vol_ratio",
                "joined from raw daily metrics (asof, 60min TTL)",
                ("oi_metrics",), "5 min source"),
)


def _ols_slope(y: np.ndarray) -> float:
    n = y.size
    if n < 2 or np.any(np.isnan(y)):
        return np.nan
    x = np.arange(n, dtype=float)
    x_m = x.mean()
    y_m = y.mean()
    denom = ((x - x_m) ** 2).sum()
    if denom == 0:
        return np.nan
    return float(((x - x_m) * (y - y_m)).sum() / denom)


def _read_oi_metrics(symbol: str, store_root: Path) -> pd.DataFrame:
    pattern = str(store_root / "raw" / "binance" / "oi" / symbol / "*.parquet")
    paths = sorted(glob.glob(pattern))
    if not paths:
        return pd.DataFrame(columns=[
            "ts_ms", "long_short_account_ratio",
            "top_trader_position_ratio", "taker_long_short_vol_ratio",
        ])
    frames = [pd.read_parquet(p) for p in paths]
    df = pd.concat(frames, ignore_index=True)
    df = df.drop_duplicates(subset=["ts_ms"], keep="first").sort_values("ts_ms")
    keep = ["ts_ms", "long_short_account_ratio",
            "top_trader_position_ratio", "taker_long_short_vol_ratio"]
    return df[keep].reset_index(drop=True)


def _join_crowding(bars: pd.DataFrame, oi: pd.DataFrame) -> pd.DataFrame:
    """Asof-join (backward) crowding cols onto bars, drop if older than 60 min."""
    if oi.empty:
        for c in ("long_short_account_ratio",
                  "top_trader_position_ratio",
                  "taker_long_short_vol_ratio"):
            bars[c] = np.nan
        return bars
    left = bars[["ts_open_ms"]].sort_values("ts_open_ms").reset_index(drop=True)
    right = oi.rename(columns={"ts_ms": "ts_oi_ms"}).copy()
    merged = pd.merge_asof(
        left, right,
        left_on="ts_open_ms", right_on="ts_oi_ms",
        direction="backward",
    )
    stale = (merged["ts_open_ms"] - merged["ts_oi_ms"]) > 60 * 60 * 1000
    for c in ("long_short_account_ratio",
              "top_trader_position_ratio",
              "taker_long_short_vol_ratio"):
        merged.loc[stale, c] = np.nan
    out = bars.copy()
    for c in ("long_short_account_ratio",
              "top_trader_position_ratio",
              "taker_long_short_vol_ratio"):
        out[c] = merged[c].values
    return out


def build_features_for(
    symbol: str,
    timeframe: str,
    store_root: Path,
    fast_ema: int = 12,
    slow_ema: int = 48,
    vol_window: int = 24,
    atr_window: int = 14,
    slope_window: int = 24,
    zscore_window: int = 24,
    funding_zscore_days: int = 30,
    oi_zscore_days: int = 30,
) -> tuple[Path, int, dict[str, int]]:
    """Compute features and write `processed/features/.../<TF>.parquet`.

    Returns (path, n_rows, non_null_counts).
    """
    src = store_root / "processed" / "bars_joined" / "binance" / symbol / f"{timeframe}.parquet"
    bars = pd.read_parquet(src).sort_values("ts_open_ms").reset_index(drop=True)
    oi = _read_oi_metrics(symbol, store_root)
    df = _join_crowding(bars, oi)

    # ---- price / return features ------------------------------------
    df["ret_1"] = df["close"].pct_change(1)
    df["ret_3"] = df["close"].pct_change(3)
    df["ret_12"] = df["close"].pct_change(12)
    df["ret_72"] = df["close"].pct_change(72)

    df["vol_close_to_close_24"] = df["ret_1"].rolling(vol_window, min_periods=vol_window).std()

    # ATR (Wilder)
    prev_close = df["close"].shift(1)
    tr = pd.concat([
        (df["high"] - df["low"]).abs(),
        (df["high"] - prev_close).abs(),
        (df["low"] - prev_close).abs(),
    ], axis=1).max(axis=1)
    df["atr_14"] = tr.ewm(alpha=1.0 / atr_window, adjust=False, min_periods=atr_window).mean()

    df["range_pct"] = (df["high"] - df["low"]) / df["close"]

    # trend
    ema_f = df["close"].ewm(span=fast_ema, adjust=False, min_periods=fast_ema).mean()
    ema_s = df["close"].ewm(span=slow_ema, adjust=False, min_periods=slow_ema).mean()
    df["ema_fast_minus_slow_pct"] = (ema_f - ema_s) / df["close"]

    log_close = np.log(df["close"])
    df["slope_ret_24"] = (
        log_close.rolling(slope_window, min_periods=slope_window)
        .apply(_ols_slope, raw=True)
    )

    # volume / taker
    rmean = df["ret_1"].rolling(zscore_window, min_periods=zscore_window).mean()
    rstd = df["ret_1"].rolling(zscore_window, min_periods=zscore_window).std()
    df["vol_zscore_24"] = (df["ret_1"] - rmean) / rstd.replace(0.0, np.nan)

    vol_b = df["volume_base"].replace(0.0, np.nan)
    df["taker_imbalance"] = (2.0 * df["taker_buy_base"] - df["volume_base"]) / vol_b

    qmean = df["taker_buy_quote"].rolling(zscore_window, min_periods=zscore_window).mean()
    qstd = df["taker_buy_quote"].rolling(zscore_window, min_periods=zscore_window).std()
    df["taker_quote_zscore_24"] = (df["taker_buy_quote"] - qmean) / qstd.replace(0.0, np.nan)

    # funding rate zscore (insufficient_data when window unfilled)
    f_window = funding_zscore_days * BARS_PER_DAY[timeframe]
    f_min = 7 * BARS_PER_DAY[timeframe]  # require 1 week of history
    fmean = df["funding_rate_ffill"].rolling(f_window, min_periods=f_min).mean()
    fstd = df["funding_rate_ffill"].rolling(f_window, min_periods=f_min).std()
    df["funding_rate_zscore_30d"] = (
        df["funding_rate_ffill"] - fmean
    ) / fstd.replace(0.0, np.nan)

    # OI features
    short_h = 1
    long_h = 24
    df["oi_pct_change_1h"] = df["oi_base"].pct_change(BARS_PER_HOUR[timeframe] * short_h)
    df["oi_pct_change_24h"] = df["oi_base"].pct_change(BARS_PER_HOUR[timeframe] * long_h)

    o_window = oi_zscore_days * BARS_PER_DAY[timeframe]
    o_min = 7 * BARS_PER_DAY[timeframe]
    omean = df["oi_base"].rolling(o_window, min_periods=o_min).mean()
    ostd = df["oi_base"].rolling(o_window, min_periods=o_min).std()
    df["oi_zscore_30d"] = (df["oi_base"] - omean) / ostd.replace(0.0, np.nan)

    # basis: not available in Phase 2/3 (no mark/index ingest yet)
    df["basis_bp"] = np.nan

    # funding window flags
    mtn = df["funding_minutes_to_next"]
    valid = mtn.notna() & (mtn >= -1) & (mtn <= FUNDING_INTERVAL_MIN + 1)
    pre = ((mtn > 0) & (mtn <= 30) & valid).astype("Int8")
    post = (
        ((FUNDING_INTERVAL_MIN - mtn) >= 0)
        & ((FUNDING_INTERVAL_MIN - mtn) <= 30)
        & (mtn > 0)
        & valid
    ).astype("Int8")
    half_tf = TF_MIN[timeframe] / 2.0
    settle = ((mtn.abs() <= half_tf) & valid).astype("Int8")
    df["pre_funding_30m"] = pre
    df["post_funding_30m"] = post
    df["funding_settle_bar"] = settle

    # ---- write ------------------------------------------------------
    feature_cols = [
        "ts_open_ms", "ts_close_ms", "exchange", "symbol", "timeframe",
        "close",
        "ret_1", "ret_3", "ret_12", "ret_72",
        "vol_close_to_close_24", "atr_14", "range_pct",
        "ema_fast_minus_slow_pct", "slope_ret_24",
        "vol_zscore_24", "taker_imbalance", "taker_quote_zscore_24",
        "funding_rate_ffill", "funding_rate_zscore_30d",
        "funding_minutes_to_next",
        "pre_funding_30m", "post_funding_30m", "funding_settle_bar",
        "basis_bp",
        "oi_base", "oi_pct_change_1h", "oi_pct_change_24h", "oi_zscore_30d",
        "long_short_account_ratio", "top_trader_position_ratio",
        "taker_long_short_vol_ratio",
    ]
    out = df[feature_cols].copy()

    out_path = store_root / "processed" / "features" / "binance" / symbol / f"{timeframe}.parquet"
    table = pa.Table.from_pandas(out, preserve_index=False)
    write_parquet_atomic(table, out_path)

    nn = {c: int(out[c].notna().sum()) for c in out.columns
          if c not in ("ts_open_ms", "ts_close_ms", "exchange",
                       "symbol", "timeframe")}
    return out_path, len(out), nn


def build_features_smoke() -> int:
    """Phase 3 smoke: build features for BTCUSDT 5m and 1h."""
    repo_root = Path(__file__).resolve().parents[2]
    store_root = repo_root / "data_layer" / "store"
    for tf in ("5m", "1h"):
        path, n, _ = build_features_for("BTCUSDT", tf, store_root)
        print(f"[features] BTCUSDT {tf} -> {path.relative_to(repo_root)} rows={n}")
    return 0
